---
version: '3.8'

services:
  text-extractor:
    build:
      context: .
      target: prod
    image: bizres-text-extractor:prod
    container_name: bizres-text-extractor-prod
    restart: unless-stopped
    environment:
      FLASK_ENV: production
      FLASK_APP: app.py
    ports:
      - 5000:5000
    volumes:
      - .:/usr/src/app