openapi: 3.0.0
info:
  title: PDF to text extractor
  description: Extracts plain text from provided PDF file
  version: 1.0.0
paths:
  /extractor:
    post:
      summary: Uploads PDF file and retrieves extracted text as a file.
      tags:
        - PDF
      requestBody:
        $ref: '#/components/requestBodies/File'
      responses:
        '200':
          description: A TXT file.
          content:
            text/plain:
              schema: 
                type: string
                # format: binary
        '400':
          $ref: '#/components/responses/ServerError'
        '415':
          $ref: '#/components/responses/ServerError'
        '500':
          $ref: '#/components/responses/ServerError'
components:
  requestBodies:
    File:
      required: true
      content:
        multipart/form-data:
          schema:
            type: object
            properties:
              file:
                type: string
                format: binary

  responses:
    ServerError:
      description: Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
        message:
          type: string
      required:
        - error
        - message
