openapi: 3.0.0
info:
  title: PDF to text extractor
  description: Extracts plain text from provided PDF file
  version: 1.0.0
paths:
  /extract:
    get:
      summary: Starts Report extraction. Downloads PDFs from Airtable, extracts text, and generates meta data. Resulting PDF, TXT, and JSON files are stored then locally.
      tags:
        - PDF
      responses:
        '202':
          description: Accepted. Returns nothing. Starts Report extraction in background.
        '400':
          $ref: '#/components/responses/ServerError'
        '415':
          $ref: '#/components/responses/ServerError'
        '500':
          $ref: '#/components/responses/ServerError'
components:
  responses:
    ServerError:
      description: Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
        message:
          type: string
      required:
        - error
        - message
